### ISSUE TITLE
most methods aren't returning a stream

### ISSUE THREAD

**Issue by mlarcher** [stevelacy/gulp-git#101]
some methods like add, checkout, commit or rm are returning a stream, while all others like tag or status don't. Is it by design ? Could it be fixed so that we can chain the commands ?

**Comment by stevelacy** [comment]
By design: https://github.com/stevelacy/gulp-git#040-introduced-breaking-changes #85

**Comment by lehni** [comment]
I understand it's by the design, but it would still have been useful to do something like this (the call to `git.tag()` in the end), and also be able to rely on the error to propagate back through the stream, without having to add a separate callback function for it.

What's the best way to do this with the current API? And am I wrong in thinking this would be of use?

```js
    gulp.src([ 'package.json', 'component.json' ])
        .pipe(bump({ version: options.version }))
        .pipe(gulp.dest('./'))
        .pipe(git.add())
        .pipe(git.commit('Release version ' + options.version))
        .pipe(git.tag('v' + options.version))
```

**Comment by lehni** [comment]
I have created a simple wrapper gulp plugin called [gulp-git-streamed](https://github.com/lehni/gulp-git-streamed) that loads `gulp-git` and wraps all the methods that don't return streams with functions that do. Here the code: https://github.com/lehni/gulp-git-streamed/blob/master/index.js#L10

You may find this useful.

**Comment by karol-f** [comment]
You can also use gulp 'done()' like this:
```
    gulp.task('git:pull', function(done) {
        return plugins.git.pull('origin', 'master', { args: '--rebase' }, function (err) {
            if (err) throw err;
            done();
        });
    });
```
