### ISSUE TITLE
Double-calling callbacks

### ISSUE THREAD

**Issue by ghost** [stevelacy/gulp-git#105]
Most of the functions double-call their callbacks (that is, they don't return when calling a callback early). This can have unintended consequences that are difficult to debug. It also prevents wrapping any of these calls in the async library, since async detects double callback calls, and throws an error.

**Comment by stevelacy** [comment]
PR?

**Comment by myloJR** [comment]
I looked, a lot of them just need to add a `return` before early callback calls. However there may be some places where that isn't sufficient (since some behavior after the early callback looks to be important), and I don't feel familiar enough with the code to dive into those cases.

**Comment by stevelacy** [comment]
ghost
