### ISSUE TITLE
Cumbersome to execute `git push --tags`

### ISSUE THREAD

**Issue by lehni** [stevelacy/gulp-git#109]
At the moment to do so, I have to pass null for `remote` and `branch`:

``` js
git.push(null, null, { args: '--tags' } )
```

It would be nice if I could just write this instead:

``` js
git.push( { args: '--tags' } )
```

**Comment by stevelacy** [comment]
PR?

**Comment by lehni** [comment]
Ditto : )

**Comment by stevelacy** [comment]
Think you could send a PR soon? I could take a look deeper into this, I just want to make sure I have the use case right :package:

**Comment by lehni** [comment]
Hi, I'm sorry for the silence. I'm using gulp-git differently in paper.js now and don't have this use-case anymore.

**Comment by stevelacy** [comment]
I'll close this now, feel free to open if needed
