### ISSUE TITLE
Callback for tag module now passes stdout as err value 

### ISSUE THREAD

**Issue by mrtimw** [stevelacy/gulp-git#110]
Hi. The changes to the tag module in [commit bcb7171](https://github.com/stevelacy/gulp-git/commit/bcb71713097596a0350d396e8470925561e234b6) means that on successful completion the callback is now called with stdout as a parameter.

As the first argument to the callback is expected to be an error value then this will be interpreted as an error by code processing the callback.

Please could you fix this to so that on successful completion the callback is called without any parameters?
Thanks

**Comment by ryanggrey** [comment]
I am seeing the same issue. The error handling function I am passing into the `tag` function is being called when there is no error (with `stdout` as a parameter). Is it meant to be `gutil.log` that `stdout` is passed to rather than the `cb` function?

**Comment by stevelacy** [comment]
@mrtimw @ryanggrey So sorry for the delay, this issue got lost in my notifications
