### ISSUE TITLE
git.push results in stream error

### ISSUE THREAD

**Issue by denver-HJS** [stevelacy/gulp-git#111]
Hi,

This could totally be something I am doing wrong because I am new to using the project, but I am receiving the following error when I try to push to my remote repo from my gulp task:

> C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623
>     var written = dest.write(chunk);
>                        ^
> TypeError: undefined is not a function
>     at write (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
>     at flow (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
>     at DestroyableTransform.pipeOnReadable (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
>     at DestroyableTransform.emit (events.js:104:17)
>     at emitReadable_ (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
>     at emitReadable (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
>     at readableAddChunk (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
>     at DestroyableTransform.Readable.push (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:149:10)
>     at DestroyableTransform.Transform.push (C:\src\git\ig\node_modules\gulp-git\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:145:32)
>     at Array.forEach (native)

The code being executed is:

```js
bump: function () {
    var branch = argv.branch || 'development';
    fs.readFile('./package.json', function (err, data) {
      if (err) { return ; }
      return gulp.src(['./package.json', './bower.json'])
        .pipe(git.add())
        .pipe(git.commit('chore(core): bump to ' + JSON.parse(data).version))
        .pipe(git.push('origin', branch, function(err) {
          if(err) throw (err);
        }));
    });
  }
```

and I am using version 1.6.0

I know this isn't necessarily the place for troubleshooting, but any help would be appreciated.

**Comment by stevelacy** [comment]
`git.push` does not take a stream (potentially yet)
https://github.com/stevelacy/gulp-git#gitpushremote-branch-opt-cb

```js
.pipe(git.commit('chore(core): bump to ' + JSON.parse(data).version))
.on('end', function() {
  git.push('origin', branch, function(err) {
    if(err) throw (err);
  });

});
```

I edited your code block to make it more readable by adding three backticks '```'

**Comment by denver-HJS** [comment]
Ah, I was wondering how I could make the code more readable. It's working with your help, so thank you very much!
