### ISSUE TITLE
git commit with specific working dir

### ISSUE THREAD

**Issue by bbaia** [stevelacy/gulp-git#113]
Hi,

Can't make work git commit in a specific directory : 
```javascript
return gulp.src('.', { cwd: 'my/specific/dir' })
           .pipe(plugins.git.commit('test', { args: '-a', quiet: false }));
```

git add works great with cwd.

- Bruno

**Comment by bbaia** [comment]
Make it work with cwd option like this : 

```javascript
return gulp.src('.', { cwd: 'my/specific/dir' })
           .pipe(plugins.git.commit('test', { cwd: './my/specific/dir', quiet: false }));
```

Did not have to do this with git add. Is this expected ?

- Bruno

**Comment by julienmartin** [comment]
awesome, thx ! save my day

**Comment by stevelacy** [comment]
That is the expected behavior, the project assumes that the commit is based on the CWD, or the `options.cwd`

`git.add()` has the cwd of the file added: https://github.com/stevelacy/gulp-git/blob/master/lib/add.js#L14

**Comment by bbaia** [comment]
OK, thanks !
