### ISSUE TITLE
Allow messages with newlines

### ISSUE THREAD

**Issue by rtomchinsky** [stevelacy/gulp-git#122]
The [Angular contributing guide](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit-message-format) demands the commit message to be in the form of

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

and [commitizen/cz-conventional-changelog](https://github.com/commitizen/cz-conventional-changelog) helps with this task. However, when the message is passed to gulp-git, it is split an array and gulp-git will send those messages with multiple `-m` arguments, and the [git docs](https://git-scm.com/docs/git-commit) state those will be interpreted as different paragraphs.

When passing a message with newlines intact, git discards everything after the first `\n`.

The git docs also say that you can use the `-F -` option to read the commit message from `stdin` and the following code works:

```js
import { spawn } from 'child_process';

const message = [
    `<type>(<scope>): <subject>`,
    `<BLANK LINE>`,
    `<body>`,
    `<BLANK LINE>`,
    `<footer>`
].join('\n');
const commit = spawn('git', ['commit', '-F', '-']);
commit.stdin.write(message, () => {
    commit.stdin.end();
});
```

I see two options:
1. Add support for `message` in commit.js to have `\n`s, using `-F -` instead of `-m`
2. When `message` is an `Array`, if an option is present (to prevent breaking compatibility with existing modules), join those and use `-F -` instead of `-m`

**Comment by stevelacy** [comment]
Sounds good, want to send a PR?

**Comment by rtomchinsky** [comment]
I'm trying to, but for some reason the `npm test` command is failing for me (on a freshly cloned version) and I can't find out why.

I'm also quite busy atm, but I'll try whenever I can.

Thanks

**Comment by stevelacy** [comment]
Ah yes, there is a bug with the git `cwd` - try: `rm .git/refs/tags/v2`

**Comment by rtomchinsky** [comment]
So, I think I got it to work. Still getting errors, but commit tests are passing so I've sent a PR #124
