### ISSUE TITLE
How to orginize input commit meassage before commit?

### ISSUE THREAD

**Issue by VitaliyAT** [stevelacy/gulp-git#130]
```
gulp.task('commit', function(){
  return gulp.src('./*')
    .pipe(git.commit('message'));
});
```

is it possible organize something like
`gulp commit 'message'`
? I need not the same commit each time.

**Comment by stevelacy** [comment]
This accepts stdin commands from the terminal: https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L45

Let me know how it goes
