### ISSUE TITLE
Possibility to use current branch for git pull

### ISSUE THREAD

**Issue by yukido** [stevelacy/gulp-git#136]
Hi!
I want to use gulp-git in our company release workflow.

What I'm wondering, though,  is why you don't allow an empty branch parameter for git pull. For us at our work, we constantly just `git pull` to bring our **current branches** up-to-date, which is what we would like to do with your plugin as well.

Are there any plans to incorporate this? I realize the advantage of having a default branch (master) to fall back on, but how about, at least, say, have a pseudovariable $current (`gulp-git pull origin $current` or something like this)?

**Comment by stevelacy** [comment]
I just added a commit to master, could you clone master and verify that it adds the needed options?

**Comment by yukido** [comment]
Looks good, thanks! I'll use the pull-origin function a lot, then!

**Comment by stevelacy** [comment]
Published to v1.12.0

**Comment by yukido** [comment]
Thanks! Works great!
