### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by nekkon** [stevelacy/gulp-git#144]
1. When I execute the code below I get an error ```Error: Command failed: git pull --depth 5 origin master``` was executed instead.

```
git.pull( 'origin' , 'master' , { args: '--depth 5' } , function (err) {
            if (err) throw err;
        });
```

2. For some reason when I git clone a variable ( src ) containing a string it runs the command ```git clone 'https://...'``` The command should not contain the ' symbol.

**Comment by stevelacy** [comment]
Probably shell-escape escaping the url inside the command: https://github.com/stevelacy/gulp-git/blob/master/lib/clone.js#L20
