### ISSUE TITLE
Gulp-git version 1.15.0 is a breaking change and should be noted

### ISSUE THREAD

**Issue by robinfhu** [stevelacy/gulp-git#151]
Gulp-git version 1.15.0 introduces a new dependency, `strip-bom-stream`.  This dependency uses ES6 syntax, and will not work with node.js version 0.10.x.  As a result, projects that still used older version of node.js broke when installing gulp-git.  

I recommend updating gulp-git to a new major version number.

**Comment by stevelacy** [comment]
Noted, thanks - I should not have merged the travis changes from that PR removing pre node 0.10...

**Comment by robinfhu** [comment]
Thanks!

**Comment by stevelacy** [comment]
published backwards fixing patch 1.15.1

**Comment by stevelacy** [comment]
published the breaking changes to 2.0.0
