### ISSUE TITLE
pull doesnt execute callback

### ISSUE THREAD

**Issue by Frankusky** [stevelacy/gulp-git#152]
The callback function is not executing, also, the quiet mode is ignored since it displays "Already up-to-date" message. 
`
git.pull({quiet: true}, function(error){
  if(error) throw error;
  console.log("test");
})
`

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-git/blob/master/lib/pull.js#L13
Add the remote and branch

**Comment by stevelacy** [comment]
Already up to date is not an error - it is the output from git.

**Comment by Frankusky** [comment]
:astonished:  thanks, that was a quick reply :smile: 

looks like this is what I was searching for:

`	git.pull("origin","", function (error) {
			console.log("test");
		})`

Closing :) thank you

**Comment by stevelacy** [comment]
glad to help!
