### ISSUE TITLE
poor error reporting

### ISSUE THREAD

**Issue by hohwille** [stevelacy/gulp-git#156]
If git command fails I get errors like this:
```
[ERROR] /home/ci/.jenkins/workspace/project-develop-ci/modules/client/gulp/release/release.js:11
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Command failed: git commit -m "..."
[ERROR] 
[ERROR]     at ChildProcess.exithandler (child_process.js:202:12)
[ERROR]     at emitTwo (events.js:100:13)
[ERROR]     at ChildProcess.emit (events.js:185:7)
[ERROR]     at maybeClose (internal/child_process.js:850:16)
[ERROR]     at Socket.<anonymous> (internal/child_process.js:323:11)
[ERROR]     at emitOne (events.js:90:13)
[ERROR]     at Socket.emit (events.js:182:7)
[ERROR]     at Pipe._onclose (net.js:484:12)
```

How, could one figure out the actual problem from such a message?
Would it be possible to print out the stdout and stderr from the git command in case it failed and also print the exit code?

**Comment by stevelacy** [comment]
The stdout and stderr are getting printed: https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L87

**Comment by hohwille** [comment]
FYI: In my case the error was that nothing had changed and git then fails with exit code 1 unless you supply ```--allow-empty```.

**Comment by hohwille** [comment]
> The stdout and stderr are getting printed: https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L87

OK, thanks. Seem I am using an old version or have the wrong settings.
I am closing as then the error seems to be on my side...
