### ISSUE TITLE
Is there any way to push to current branch, without specifying the branch name?

### ISSUE THREAD

**Issue by masoomulhaqs** [stevelacy/gulp-git#161]
Hi,

Let's assume that I working on develop branch, I might be having many other branches (develop1, feature1, ...).

However, I want to push the changes to the current branch (develop) without specifying the branch name in the below example. 

```javascript
gulp.task('push', function(){
  git.push('origin', 'master', function (err) {
    if (err) throw err;
});
```

Is there any way to do this?

**Comment by stevelacy** [comment]
Not currently, PRs welcome.
