### ISSUE TITLE
Git clone not finished before next task

### ISSUE THREAD

**Issue by d-luk** [stevelacy/gulp-git#168]
I am trying to create a gulp task which uses files from another repository. I need to clone that repository each time the task runs (the clone will be deleted after each execution). Please see the example below:

```
gulp.task('git-clone', function () {
    return git.clone(
        'https://link.to/my/repo.git',
        { args: './git' },
        function (err) { if (err) throw err; }
    )
});

gulp.task('default', ['git-clone'], function () {
    return gulp.src('./git/**')
        // Do things
        .pipe(gulp.dest('./copy'))
});
```

When I run the `default` task I depend on the `git-clone` to be finished, but this is not the case. This results in the default task not working. The 'copy' folder is not created at all.

**Comment by stevelacy** [comment]
https://github.com/gulpjs/gulp/blob/master/docs/API.md#accept-a-callback

**Comment by d-luk** [comment]
@stevelacy Totally forgot about that. It works, thanks!
