### ISSUE TITLE
Get current branch name?

### ISSUE THREAD

**Issue by tbenyon** [stevelacy/gulp-git#175]
Might be cool to be able to get the branch name.

In my case it is so my build process makes sure deploys can only be run from the master branch.

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-git/issues/141#issuecomment-268570175

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-git/commit/d54339b7305acc45a10dd0c1c33f852a6d2e5356
