### ISSUE TITLE
git add is broken in Node 8

### ISSUE THREAD

**Issue by luthv** [stevelacy/gulp-git#177]
git add is throwing `TypeError('"cwd" must be a string')` error on Node 8.

Basically process.cwd is now a function in Node 8
[https://nodejs.org/api/process.html#process_process_cwd](https://nodejs.org/api/process.html#process_process_cwd)

**Comment by stevelacy** [comment]
it has been a function since before node v4, somehow it got in without the params. 
Thanks for reporting.
