### ISSUE TITLE
Error: i can't commit

### ISSUE THREAD

**Issue by qhxin** [stevelacy/gulp-git#182]
this is my gulp code on my Mac
```
gulp.task('private-commit-changes', () => {
  return gulp.src('./*')
    .pipe(git.commit('commitTest', { args: '-a' }));
});
```

it echo an error on console 
`fatal: Paths with -a does not make sense.`

my old version is: 2.5.2.
then i use the newest version.
it cause the error.
then i back to the version2.5.2, the error still exists.

**Comment by stevelacy** [comment]
I don't think you are actually using 2.5.2 when you say you went back to the old version. Ensure npm did not use a cached version.

Remove the `-a` and it will work.

**Comment by qhxin** [comment]
now i use these codes, it works ok

```
gulp.task('private-commit-changes', () => {
  return gulp.src('.')
    .pipe(git.add())
    .pipe(git.commit('commitTest'));
});
```
