### ISSUE TITLE
How to clone with a specified branch?

### ISSUE THREAD

**Issue by Sabre36** [stevelacy/gulp-git#185]
As our repo is growing, I'd like to specify a branch which is the equivalent to:

_git clone -b my-branch git@github.com:user/myproject.git_

Is this possible in git.clone(...)?

**Comment by stevelacy** [comment]
Try this:

```js
git.clone('git@github.com:user/myproject.git', { args: 'my-branch' })
```

**Comment by stevelacy** [comment]
```js
    var repo = 'git://github.com/stevelacy/gulp-git';
    git.clone(repo, {args: '-b master ./dest'});
```

**Comment by jcarpenter** [comment]
Might be worth adding this to the docs? Glad I found this answer, but searching issues not ideal.

**Comment by stevelacy** [comment]
@jcarpenter PR Welcome
