### ISSUE TITLE
Cannot use '-a' anymore for commit

### ISSUE THREAD

**Issue by ustieber** [stevelacy/gulp-git#188]
Since gulp-git@2.6.0, and opt.args contains '-a', the git command is constructed as

  git commit -m "my comment" -a .

Executing this command leads to a git error message

  fatal: Paths with -a does not make sense.

When the trailing '.' is omitted, the command works again as expected.

The issue has been introduced by commit fc3ca0d5529e9347a29ff50ebc93bd7f003ea641, always appending a '.' to the git commit command.

**Comment by stevelacy** [comment]
That particular change was required for git support on windows.
I see a two options for this going forward, either add an option to add the location suffix automatically, or add an option to have a raw commit command without any of the helper functions. 
I personally would rather break the 2.6.0 and add an option to add the location and keep the base command.

**Comment by ustieber** [comment]
What about adding the '.' to the command line only if 'disableAppendPaths' is 'false'? As it is done in line 70? From my point of view, that would solve the issue right away and without breaking anything. With '-a' in opt.args, 'disableAppendPaths' needs to be 'true' anyway.

**Comment by stevelacy** [comment]
Want to send a pull request?

**Comment by stevelacy** [comment]
e840a398b7bef1a737aaeeb29eba31d7fd6584ad
