### ISSUE TITLE
how can I checkout a file

### ISSUE THREAD

**Issue by hadifarnoud** [stevelacy/gulp-git#190]
before commiting I'd like to discard changes to a file. I'm doing it with `git checkout -- index.html` 
how can i do that with gulp-git?

**Comment by stevelacy** [comment]
https://github.com/stevelacy/gulp-git#gitcheckoutfilesopt
https://github.com/stevelacy/gulp-git/blob/master/lib/checkoutFiles.js#L14

```js
gulp.src('./index.html')
  .pipe(git.checkoutFiles());
```
