### ISSUE TITLE
Add rebase command

### ISSUE THREAD

**Issue by comlaterra** [stevelacy/gulp-git#200]
See [documentation](https://git-scm.com/docs/git-rebase)

**Comment by stevelacy** [comment]
Use exec for non implemented commands: https://github.com/stevelacy/gulp-git#gitexecopt-cb

**Comment by comlaterra** [comment]
In this case I recommend to use the native NodeJS way to run commands: https://nodejs.org/api/child_process.html#child_process_child_process

To run `exec` from a library that the only thing that does is to add an interface to a native command defeats the reason why this library should exist.
