### ISSUE TITLE
How to clone to specific folder?

### ISSUE THREAD

**Issue by maridob** [stevelacy/gulp-git#32]
var git = require('gulp-git'); 
// Clone a remote repo
 gulp.task('clone', function(){
 git.clone('https://git-location', './apps/');
});

This one is running but it is creating an undefined folder and copying all the files there. Am I doing something wrong or is this possible?

**Comment by matbo81** [comment]
I want:
call a git commit command to a repo in another repo than my gulpfile is.
But that ways (1,2) not working:
1.)
gulp.task('commit', function() {
  gulp.src('folder_git')
  .pipe(git.commit(commit_msg, {args: 'folder_git', maxBuffer: 200 * 1024, quiet: true, disableMessageRequirement: false, disableAppendPaths: false, multiline: false}));
});
2:)
gulp.task('commit', function() {
  gulp.src('folder_git')
  .pipe(git.commit(commit_msg, {args: '', cwd:'folder_git', maxBuffer: 200 * 1024, quiet: true, disableMessageRequirement: false, disableAppendPaths: false, multiline: false}));
});
All it does is to call the commit on that repo the gulpfile is...
(with clone, it works perfectly)
Have someone an idea?
