### ISSUE TITLE
Commit doesn't fire `end`

### ISSUE THREAD

**Issue by bfricka** [stevelacy/gulp-git#49]
It looks like this hasn't worked for awhile (since before the 0.5.1 refactor). I've been chasing this for awhile and the `commit` method simply doesn't resolve in a way that gets gulp to fire an `end` event.  This is fine, but if it doesn't fire `end` it should at least accept a callback like some of the other tasks.

The docs seem to imply `end` is fired (by returning the stream).

The lack of callback or `end` make it impossible to orchestrate synchronous tasks which depend on `commit`.

Here's a quick example using bluebird promises to commit then tag:

```js
var q = require('bluebird');

function commit (src) {
  return new q(function (resolve, reject) {
    gulp
      .src(src)
      .pipe(git.commit('msg'))
      .on('error', reject)
      .on('end', resolve);
  });
}

function tag () {
  return new q(function (resolve, reject) {
    git.tag('v0.0.1', 'tag', function(err) {
      if (err) return reject(err);
      resolve();
    });
  });
}

commit('./something').then(tag).catch(errHandler);
```

In this case, `tag` never fires. `errHandler` will fire if there is in fact an error.

There really has to be a way to hook into `commit`. One way would be to pass a callback as in other tasks. Additionally, these commands could all accept an `'end'` option which tells them to fire end when they complete. This would obviously just call `stream.resume()` if true;

For example, the above can be made to work:

```js
function commit (src) {
  var stream;

  return new q(function (resolve, reject) {
    gulp.src(src)
      .pipe(stream = git.commit('msg'))
      .on('error', reject)
      .on('end', resolve);

    stream.resume();
  });
}
```

Finally, I realize that the above can be accomplished simply by piping `commit` to `tag`, and I'm sure this works for most cases. However, having this flexibility is nice.  More importantly, it's the sort of flexibility that you'd expect to have simply due to the fact that so many other commands have a callback param. With most gulp tasks, it's sort of implied that `gulp.dest()` will be called, which takes care of `stream.resume()`, but `gulp.dest()` doesn't really make sense here. Thus, I think makes sense to have solid hooks into the streams' lifecycle.

Let me know your thoughts and if you're amenable, I'll open a pull request.

**Comment by openjck** [comment]
+1

**Comment by icvitkovac** [comment]
++

**Comment by jlukic** [comment]
++

**Comment by stevelacy** [comment]
@bfricka do you want to send the PR?

**Comment by bfricka** [comment]
Thanks for bringing this up. I had totally forgotten. I'll try to put one out tonight.

**Comment by am** [comment]
Will this work for `git.exec` also?

**Comment by stevelacy** [comment]
Sorry for the long wait - I just hack-patched `gulp-git` as through2 was not fixed.

**Comment by stringparser** [comment]
Great, did you report it?

**Comment by stevelacy** [comment]
@stringparser I was about to, but they closed 2 other issues regarding it.

**Comment by stringparser** [comment]
@stevelacy thanks, I've been looking at https://github.com/rvagg/through2/issues/37. It seems intended, the workaround is to call resume if the stream is not piped anywhere else it will be paused, I forgot that.

**Comment by stevelacy** [comment]
Indeed, in gulp plugins case it does not make sense to have the users add that.
