### ISSUE TITLE
Allow tag to accept a stream

### ISSUE THREAD

**Issue by jasonkarns** [stevelacy/gulp-git#53]
It would be more gulp-like for tag to accept a stream, similar to how `gulp-tag-version` accepts a stream. It assumes that the incoming stream is JSON with a top-level `version` property which is used.

Couple this with making message optional (with a reasonable default) would make a more terse use-case possible: `.pipe(tag())`

**Comment by eseceve** [comment]
What about if I want to do a gulp task like this?:

```javascript
var git = require('gulp-git');
gulp.task('myTask', function() {
  return gulp.src(['/my/files.ext'])
    .pipe(git.add())
    .pipe(git.commit('my message')
    .pipe(git.tag(myVersion, 'my message')
    .pipe(git.push('origin', 'master', {args: '--tags'}));
});
```

**Comment by dreadcast** [comment]
@eseceve 
Did you manage to do that?
I always get the previous commit tagged and pushed. But the current commit is not pushed.

I'm getting this error message: 
TypeError: undefined is not a function"

which ties in this line:
.pipe(git.tag(v, message)) is undefined...

**Comment by stevelacy** [comment]
@dreadcast  Tag is not a stream, and won't be changed to a stream.
https://github.com/stevelacy/gulp-git/blob/master/examples/gulpfile.js#L64

**Comment by dreadcast** [comment]
I've set gulp-git version to 0.2.0 as used in contra:
https://github.com/bevacqua/contra/blob/master/package.json
and @eseceve example just works, except that push option is a string : '--tags'

**Comment by dreadcast** [comment]
I rolled gulp-git back to version 0.2.0 and @eseceve example almost works... I could add, commit and tag the latest commit. But I can't get push() to work :(

**Comment by dreadcast** [comment]
@stevelacy 
Thank for your example, I will try it tomorrow and then use the latest gulp-git version again !

**Comment by eseceve** [comment]
@dreadcast https://gist.github.com/eseceve/1461a561b4184dd6e2da

**Comment by dreadcast** [comment]
@eseceve 
I got server errors with @stevelacy 's example then I digged into your recipe and it works great!
