### ISSUE TITLE
Support git config

### ISSUE THREAD

**Issue by nkoterba** [stevelacy/gulp-git#64]
First, excellent gulp plugin!  Really helpful and useful so thanks for your effort.

Second, is it possible to add support for 'git config' to the plugin?

Here's the git man page for it: http://git-scm.com/docs/git-config

Here's an example of how it could be used:
```javascript
git.config({args: 'core.sparsecheckout true'}, function (err) {
		if (err) throw err;
	});
```

**Comment by stevelacy** [comment]
Adding more non-file based git commands would create a much harder to manage massive plugin. This goes against gulp guidelines.

Referring to #56, use the `git.exec` function: https://github.com/stevelacy/gulp-git/blob/master/lib/exec.js

**Comment by nkoterba** [comment]
@stevelacy Ok. Thanks for the info! I searched the issues for 'config' and nothing came up so I created this one.  In the end, I resulted to using `node.process_child.exec` which it looks like git.exec does internally.  I missed the git.exec as it was down the page and past the 'init' documentation section which is where I was looking to setup the git repo after the 'init' call.

**Comment by stevelacy** [comment]
Ah, yes it is rather hard to notice.

**Comment by gucong3000** [comment]
I 'd like push a PR to do this.

```js
const git = require('gulp-git')({
  gitDir: gitDir, // `--git-dir` from `git`.
  pager: false,   // `--no-pager` from `git`.
  config: {       // `-c` from `git`, key-value pairs
    "core.sparsecheckout": true,
    "user.email": "you@example.com",
    "user.name": "Your Name",
  }
});

git.commit();
```

**Comment by gucong3000** [comment]
alessioalex/git-spawned-stream#4

**Comment by stevelacy** [comment]
I do not want to increase the API of this project.
