### ISSUE TITLE
Promise Support

### ISSUE THREAD

**Issue by dcunited08** [stevelacy/gulp-git#66]
It would be very useful if this library supported promises, does anyone else find it useful?  Basically if a cb isn't included in the call, it should return a promise that is resolved with something useful (or true) when the task is complete.

**Comment by stevelacy** [comment]
At the current state I do not have any intentions to add promise support.
It would just make the (already large) plugin more convoluted.

**Comment by dcunited08** [comment]
Thanks for the quick response, I'll just wrap the functions I use for now.
