### ISSUE TITLE
Problem While Installing gulp

### ISSUE THREAD

**Issue by KaranSofat** [stevelacy/gulp-git#67]
I run this Command npm install gulp -g 

npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 2.0.8
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-install-checks requires npmlog@'0.1 || 1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npmlog,
npm WARN unmet dependency which is version 0.0.3
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/readable-stream requires inherits@'~2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/inherits,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/npm-package-arg requires semver@'4' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/semver,
npm WARN unmet dependency which is version 2.0.8
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream requires inherits@'~2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/inherits,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream requires inherits@'~2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/inherits,
npm WARN unmet dependency which is version 1.0.0
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/sha/node_modules/readable-stream requires inherits@'~2.0.1' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/npm/node_modules/inherits,
npm WARN unmet dependency which is version 1.0.0

**Comment by stevelacy** [comment]
irrelevant to this project
