### ISSUE TITLE
commit followed by tag tags wrong commit

### ISSUE THREAD

**Issue by elexx** [stevelacy/gulp-git#69]
I'm trying to write a release task, which should bump the version, add the changed files to files, commit them and tag the commit. This is the code I wrote:
```javascript
gulp.task('release', function () {
	var version = semver.inc(require('./package.json').version, 'patch');

	return gulp.src(['./package.json', './bower.json'])
		.pipe($.bump({ version: version }))
		.pipe(gulp.dest('./'))
		.pipe($.git.add())
		.pipe($.git.commit('chore(release): v' + version))
		.pipe($.git.tag('v' + version, 'Version ' + version));
});
```
But somehow not the new but the commit before gets tagged. My git log looks like this:
```
* 30255da - chore(release): v0.0.2 — (HEAD, master)
* ec0d554 - init — (tag: v0.0.2)
```
I would have expected something like this:
```
* 30255da - chore(release): v0.0.2 — (HEAD, master, tag: v0.0.2)
* ec0d554 - init
```
Is this behavior expected or did I find a bug? And if it is by design, how could I solve my problem?

**Comment by stevelacy** [comment]
try:

```js
git.add({args: '-a'})
```

As it depends on the git version.

**Comment by elexx** [comment]
The files get added and committed in the `chore(release): v.0.0.2` commit. But the tag I create afterwards is on the previous `init` commit and not on the new `chore(...` commit.
It looks like the `$.git.tag()` line gets executed before the `$.git.commit()` finishes.

**Comment by MonkeyDo** [comment]
You could have a look at how tagging is handled in the PR #58 example, using ```.on('end', function () { git.tag( [...] ) })```

**Comment by elexx** [comment]
Thanks @MonkeyDo that works!
But I'm still wondering if this is the expected behavior or not?

**Comment by stevelacy** [comment]
@MonkeyDo is right, I did not notice what the tag line was doing, just the add/commit.

Not all gulp-git functions are pipeable streams, tag, push, etc are functions to occur in an `on` event.

**Comment by elexx** [comment]
Thanks
