### ISSUE TITLE
Option to disable commit message check

### ISSUE THREAD

**Issue by jimthedev** [stevelacy/gulp-git#72]
There are some cases where raw commit arguments might be passed in. Although requiring a commit message is a sensible default, it would be nice to have an option to override this check.

The code would look something like this assuming that commitArgs is the raw arguments to go to git commit:

```
.pipe(git.commit(undefined, {args: commitArgs, disableMessageRequirement: true}))
```

**Comment by stevelacy** [comment]
Added
