### ISSUE TITLE
Adding extra arguments to git command such as --work-tree and --git-dir

### ISSUE THREAD

**Issue by Glish** [stevelacy/gulp-git#74]
Hi,  I am not sure if this is an issue, a new feature or just something I am doing wrong, but I am using gulp-git in a current project and have hit upon a problem. No matter where I try to include the extra arguments, I only get errors when I try to use --work-tree and --git-dir in my git task.

I have made various attempts at adding them as args or cwd, but no luck.

The command line request I am trying to recreate in gulp is:
git --git-dir=../git_repos/dev --work-tree=../dev status

I have asked a question on stackoverflow, just in case anyone there might no anything and that has the full details in it:  http://stackoverflow.com/questions/29743031/using-gulp-git-how-to-use-git-dir-and-work-tree-when

**Comment by stringparser** [comment]
Try with [git.exec](https://github.com/stevelacy/gulp-git#gitexecopt-cb) or [git.status](https://github.com/stevelacy/gulp-git#gitstatusopt-cb)
