### ISSUE TITLE
Add `git.describe` command

### ISSUE THREAD

**Issue by IcanDivideBy0** [stevelacy/gulp-git#79]
Usefull to get the latest tag.

```sh
git describe --abbrev=0 --tags
```

**Comment by IcanDivideBy0** [comment]
Nevermind, `git.exec` is enouth for that!

**Comment by davidmaxwaterman** [comment]
I'd quite like to know how you made 'git.exec' work for this.

**Comment by IcanDivideBy0** [comment]
```
git.exec({
  args: 'describe --abbrev=0 --tags',
  quiet: true
}, (err, latestTag) => { ... });
```

**Comment by stevelacy** [comment]
Want to add it to the examples?

**Comment by IcanDivideBy0** [comment]
I think the log example is already enouth. This one won't add anything more relevant to the doc.
