### ISSUE TITLE
git.commit()'s approach for listing files as arguments breaks on Windows

### ISSUE THREAD

**Issue by andrewmcwatters** [stevelacy/gulp-git#81]
Hello from North Scottsdale!

```
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git commit -m "..."
"app.js" "app.js.map" lib "package.json" routes "lib/database.js" "lib/database.
js.map" "routes/api.js" "routes/api.js.map""
```

Pretty sure a different escape method needs to be taken for this to work on Windows.

**Comment by stevelacy** [comment]
Hello from Pluto.

Interesting... we are using [any-shell-escape](https://github.com/boazy/any-shell-escape) to escape the input filenames.

It appears that the string interpolation is transforming to double quotes on the win32 console, then it is added to the escaped paths.
https://github.com/stevelacy/gulp-git/blob/master/lib/commit.js#L52

I'll try to debug this from UNIX, if you don't mind testing and debugging with your win system.

**Comment by andrewmcwatters** [comment]
totes magotes

**Comment by andrewmcwatters** [comment]
Using [grunt-build-control](https://github.com/robwierzbowski/grunt-build-control) as an alternative.
