### ISSUE TITLE
Add an ls-files command

### ISSUE THREAD

**Issue by bendavis78** [stevelacy/gulp-git#83]
ls-files has some handy flags, it would be good as a starting point for src files to feed into gulp. For example, if I wanted to copy non-git-ignored files to .build, I could do:

```javascript
git.lsFiles({args: '--others -i --exclude-standard'})
    .pipe(gulp.dest('.build'))
```

**Comment by stevelacy** [comment]
What would the output be, an object or array? Stream or function?

**Comment by bendavis78** [comment]
I imagine the output would be a vynil stream.

**Comment by stevelacy** [comment]
PR?
