### ISSUE TITLE
Is this a gulp plugin or it can be used anywhere?

### ISSUE THREAD

**Issue by stevemao** [stevelacy/gulp-git#84]
https://github.com/gulpjs/plugins/issues/196
It looks like this could be used anywhere.

**Comment by stevelacy** [comment]
This is a gulp plugin.


It requires the use of a gulp vinyl stream to function, though it does contain additional functions which you could probably require and use, just like any large gulp-plugin.

**Comment by stevemao** [comment]
Thank you :)
