### ISSUE TITLE
Chaining several commands?

### ISSUE THREAD

**Issue by alexklibisz** [stevelacy/gulp-git#85]
Hi, excuse me if this is somewhere in the docs, but I couldn't find an example to help with this.

Is there any way to chain several commands together, without nesting several callback functions?

For example, I would like to automate a deployment process that involves the command sequence:

> git checkout deploy-dev
> git merge master
> git push origin deploy-dev
> git checkout master

Right now I'm doing this like so:

```
git.checkout('deploy-dev', function() {
  git.merge('master', function() {
    git.push('origin', 'deploy-dev', function() {
      git.checkout('master');
    });
  });
});
```
But obviously this is not preferable.

I've also tried by starting with ```gulp.src('./*')``` then pipe-ing through the sequence of gulp commands, but I get the error:
```
TypeError: Cannot read property 'on' of undefined
```

Thanks in advance for your help and nice work on this package.

**Comment by stevelacy** [comment]
Certain functions are through streams, allowing the gulp.src to pass files through.
The rest are normal callback functions.
`add`, `checkoutFiles`, `commit`, and `rm` are streams that take a gulp src.

**Comment by alexklibisz** [comment]
So I suppose they could be wrapped in promises to avoid making the nested callbacks. I'll try that and post back.

**Comment by hisankaran** [comment]
I know it is pretty old issue. But posting a simpler solution for others benefit.

```
const util = require('util');
const git = require('gulp-git');

const methods = [
  'addRemote', 'removeRemote', 'addSubmodule', 'updateSubmodule',
  'push', 'pull', 'fetch', 'clone', 'tag', 'branch', 'checkout', 'merge',
  'reset', 'clean', 'exec'
];

methods.forEach(function (method) {
  var func = git[method];
  git[method] = util.promisify(func);
});
```

Then you can define an async task as described here: https://gulpjs.com/docs/en/getting-started/async-completion#using-async-await.
