### ISSUE TITLE
Having an empty console.log

### ISSUE THREAD

**Issue by Avcajaraville** [stevelacy/gulp-git#87]
Hi !

Im struggling with this problem and I don't know why it is happening.

Im trying to build a custom plugin. Everything is fine and working. The only problem Im having is that I alway have an empty log on the console. Since this plugin its meant to work with other plugins, I don't want to have the console "polluted".

This happens also with the example provided on the docs.

This is the dummy task I have so far:

```javascript
gulp.task('tag', function(){
  git.tag('v1.1.225', 'Version message', function (err) {
    if (err) {
      throw err;
    }
  });
});
```

When I do a gulp tag, this is my output:

![captura de pantalla 2015-08-13 a las 10 23 19](https://cloud.githubusercontent.com/assets/2271201/9245560/5dc2969e-41a5-11e5-93c9-3b368e41bb2a.png)

That last line logged on the console is what is bugging me. 

Any ideas about why it happens and how can I avoid it ?

Thanks !

**Comment by stevelacy** [comment]
Git is returning the output as a newline, even though it is empty.

**Comment by Avcajaraville** [comment]
Why would be this a desired feature ?

Also, why its not possible to tag without message ?

Thanks a lot !
