### ISSUE TITLE
pull should handle @{u}

### ISSUE THREAD

**Issue by plcstpierre** [stevelacy/gulp-git#91]
http://stackoverflow.com/questions/18960760/reference-current-branch-and-origin-current-in-git-alias

**Comment by stevelacy** [comment]
Please add an example.
All args are passed through: https://github.com/stevelacy/gulp-git/blob/master/lib/pull.js#L18
The SO question you linked to only includes information for aliases

**Comment by plcstpierre** [comment]
@{u} point on the tracked branch.

I said pull in the initial request, but the problem is easier to explain on the push command.

The push command expect a remote as the first argument and a branch on the second argument.

With @{u} you have neither. I do not see how it could work because you default on origin and master if they are not specified.
