### ISSUE TITLE
ENOENT whenever trying to git.clone into a folder that still doesn't exist

### ISSUE THREAD

**Issue by fernandofleury** [stevelacy/gulp-git#95]
So, I am using `exec` to clone a repo and place it on a specific folder (in this case is `folder1/2/3/4/5` inside of the project), and it works just fine.

But, whenever i try to achiev the same using git.clone, i get `ENOENT` error. The task is:

```javascript
git.clone(repo, {
cwd: '1/2/3/4/5'
}, cb);
```

Honestly I'm not sure if I'm doing this the right way, but the docs aren't so clear about this.

**Comment by stevelacy** [comment]
Can you confirm that the folder structure and repo name are correct?

Can you also show your exec function?

**Comment by fernandofleury** [comment]
```javascript
gulp.task('install, function(cb) {
return exec('git clone repo.git dest', function(err, stdin, stdout) {
    if (err) {
      console.log(err);
    }
    cb();
  });
});
```

yeah, the folder structure is used as a `paths` object. I was using previously on the exec task as well.

**Comment by stevelacy** [comment]
Did you add the cwd to the raw exec function?
I'm trying to find the similarities, which might cause the issues.

**Comment by fernandofleury** [comment]
the `cwd` is represented as the `dest` on the snippet

**Comment by fernandofleury** [comment]
basically im doing `git clone repo 1/2/3/4/5`, just as the same as the `git.clone()` example

**Comment by stevelacy** [comment]
The cwd is the node working directory, not the destination folder for the git command.
It is failing with `ENOENT` resource not found since the folder does not exist for it to change directories to.

Add the destination to the args option, `git.clone(repo, {args: '1/2/3/4/5'})`.

I will add the example to the repo for sub folders, thanks for bringing it up!

**Comment by fernandofleury** [comment]
Thank you, Sorry for my miscomprehension.
