### ISSUE TITLE
Add a diff command

### ISSUE THREAD

**Issue by sebastienbarre** [stevelacy/gulp-git#97]
Howdy. I was wondering if you had the `diff` command in mind, somewhere on your roadmap?
If that is not the case, do you have some design thoughts about it, or would you recommend another command in this repo a `diff` PR could find some inspiration from?
Thanks

**Comment by stevelacy** [comment]
What would the output be from the diff command, just a git diff?

```js
git.diff(function(err, diff) {
  // diff => the following diff
})
```
```diff
diff --git a/main.rs b/main.rs
index 338f4c8..5db4970 100644
--- a/tcp.rs
+++ b/rcp.rs
@@ -22,6 +22,7 @@ fn tcp_stream(mut stream: io::TcpStream) -> io::IoResult<()> {
 
         let mut input = buf.slice(0, got).to_string();
         println!("{}", input);
+        try!(stream.write(buf.slice(0, got)));
     }
     Ok(())
 }
```

A flat diff (no editor/viewer) can be created with `git  --no-pager diff`

**Comment by sebastienbarre** [comment]
Just a git diff, yes. Full disclosure, commitizen/cz-cli#7 is trying to find out if some files were staged. It is using `gulp-git` under the hood. Somebody suggested trying `git diff --cached`, but the author pointed out that `gulp-git` had no support for the `diff` command yet, hence me chiming in. But now I realize we could use your `git.exec` instead, right? (aka `git.exec({args : 'diff --cached'}, function (err, stdout) { ... });)`). Thanks.

**Comment by stevelacy** [comment]
Yes, `git.exec` will do that quite well.

**Comment by sebastienbarre** [comment]
Thanks. (@jimthedev). 
Closing it, no need to burden you then :)

**Comment by jimthedev** [comment]
Sweet, thanks @stevelacy @sebastienbarre.

**Comment by stevelacy** [comment]
Glad to help anyway I can on your project :smile:

**Comment by jimthedev** [comment]
Haha, my project wouldn't exist w/o you, so, tip of the hat.

**Comment by jimthedev** [comment]
Just a follow up for anyone who stumbles upon this thread in the future. If you want to capture output from diff to determine if there are staged files, you'll have to use `git diff --cached --exit-code` since by default cached mode runs in interactive mode. The `--exit-code` sends the results to stdout. Cheers.

**Comment by stupidisum** [comment]
Maybe need another diff....
get all `git-diffed` files for `code style check`

**Comment by gucong3000** [comment]
@Stupidism @stevelacy
> Maybe need another diff....
> get all git-diffed files for code style check

I like to made a PR,

**Comment by stevelacy** [comment]
What is the output of this proposed diff command?

**Comment by gucong3000** [comment]
@stevelacy 
![image](https://cloud.githubusercontent.com/assets/1171691/22721365/3e95f268-edeb-11e6-9ade-3d9f999a38a9.png)

**Comment by stevelacy** [comment]
How does `git.exec` not support this?

**Comment by gucong3000** [comment]
there is some step:
1. run `git.exec("diff 1.0.0... --raw -z --diff-filter=ACMR")`
1. use a regexp parse stdout
1. run `git.exec("cat-file blob 56b4c63")` for each file, set `file.contents = catFileStdout`

**Comment by gucong3000** [comment]
git.exec just retuen result of stdout, but we need a stream of vinyl File objects.

**Comment by stevelacy** [comment]
Okay, you can send a PR. 
Follow the `add.js` for structure: https://github.com/stevelacy/gulp-git/blob/master/lib/add.js
The diffed files should be sent in on the input stream. The output should not change the file.contents, but rather add a `diff` key to the file object.

```js
File: {
  contents: Buffer(),
  path: './path',
  diff: Buffer() // git diff
}
```
Then a sub-plugin can pull the `diff` key and pass it through whatever parser.

**Comment by gucong3000** [comment]
@Stupidism 
> Maybe need another diff....
> get all `git-diffed` files for `code style check`

I made a [PR](https://github.com/stevelacy/gulp-git/issues/149) for this case.

See this file: [gulpfile.js](https://github.com/gucong3000/gulp-git/blob/git_diff_flow/gulpfile.js)
