### ISSUE TITLE
Question: Re

### ISSUE THREAD

**Issue by jimthedev** [stevelacy/gulp-git#98]
Hi Steve,

I am planning to put in a PR to address [this issue](https://github.com/commitizen/cz-cli/issues/8) but wanted to ask for some input beforehand. When using .commit(), it is possible that a repo will have pre-commit hooks configured. These hooks run before gulp-git's commit() callback is executed. 

These hooks can, and often are long running if, for example, they execute a bunch of tests. Currently, the output gets swallowed until the commit is finished, almost appearing as if the process has hung. Then all of a sudden all of the results appear on the screen in one large block. 

In these scenarios I think we'd ideally be able to incrementally pipe the output of the exec command to the console, or even better, emit a 'data' event that sends an incremental progress update.

I think I'm leaning towards the second option but I wanted to confirm that this was a good choice. The problem is, I'm not sure how to use self.emit to send the data back out of .commit(). I see self.emit('end') but obviously it doesn't pass anything out. Do you know if this is possible? 

Here is an example of what the change would ideally look like:

```
// Currently we don't do anything with the returned value of exec:
// exec(...) {}

// In the new changes we'd get the return value...
var execLogger = exec(...) {}

// Then listen to the data as it comes back...

// Something new came from stdout
execLogger.stdout.on('data',function(data){

  // Option 1: We could just log out the data as it comes back. This is intrusive, however.
  console.log(data);
});

// Something new came from stderr
execLogger.stderr.on('data',function(data){
  
  // Option 2: We could emit the data back up, allowing the consumer to ignore it or not 
  self.emit('data', data);
});

```

Anyhow I know that most of this works, I just wasn't sure of the gulp specifics surrounding .emit. Thanks.

**Comment by stevelacy** [comment]
Sounds like switching commit from `exec` to `spawn` would do it, as it would gutil.log the output as it flows in without needing to emit any data (close the stream) to gulp's stream.
